using System.Text;
using KiwiMind.Application.Common.Interfaces;
using KiwiMind.Application.Retrieval;

namespace KiwiMind.Infrastructure.Chat;

public class FakeChatCompletionService : IChatCompletionService
{
    public Task<string> GenerateAnswerAsync(
        IReadOnlyList<ChunkSearchResultDto> context,
        IReadOnlyList<ChatMessage> history,
        string question,
        CancellationToken cancellationToken)
    {
        if (context.Count == 0)
        {
            return Task.FromResult(
                $"I couldn't find any relevant passages in this knowledge base to answer: \"{question}\".");
        }

        var sb = new StringBuilder();
        sb.AppendLine($"Based on the retrieved context, here is what I found relevant to: \"{question}\"");
        sb.AppendLine();

        for (var i = 0; i < context.Count; i++)
        {
            var excerpt = context[i].Content.Length > 200 ? context[i].Content[..200] + "…" : context[i].Content;
            sb.AppendLine($"[{i + 1}] {excerpt}");
        }

        sb.AppendLine();
        sb.AppendLine("(This answer was generated by a local placeholder chat provider for pipeline verification; swap IChatCompletionService for a real LLM to generate genuine answers.)");

        return Task.FromResult(sb.ToString());
    }
}
